import os

NOTION_INTEGRATION_TOKEN = os.environ.get('NOTION_INTEGRATION_TOKEN')
NOTION_DATABASE_ID = os.environ.get('NOTION_DATABASE_ID')
GITHUB_AUTH_TOKEN = os.environ.get('GITHUB_AUTH_TOKEN')

GITHUB_MY_NAME = os.environ.get('GITHUB_MY_NAME')

GITHUB_TEMPLATE_REPO_NAME = os.environ.get('GITHUB_TEMPLATE_REPO_NAME')
GITHUB_TEMPLATE_OWNER_NAME = os.environ.get('GITHUB_TEMPLATE_OWNER_NAME')

LOCAL_CLONING_PATH = os.environ.get("LOCAL_CLONING_PATH")
SCREENSHOTS_PATH = os.environ.get("SCREENSHOTS_PATH")
